### ISSUE TITLE
"pw_filled.csv" File missing in the library.

### ISSUE THREAD

**Issue by hemangjoshi37a** [ITMO-NSS-team/fedot_electro_ts_case#2]
"pw_filled.csv" File missing in the library. For running the file ts_case_others.
[https://hjlabs.in/](https://hjlabs.in/)

**Comment by jasonchanhku** [comment]
pw.csv is missing as well

**Comment by nicl-nno** [comment]
Hi!

At last, we added the files since they are become public.
However, this example is quite obsolete from technical side (since it aimed to fedot 0.3 and current version is 0.6.1+). You can find actual examples in https://github.com/ITMO-NSS-team/fedot-examples/tree/main/notebooks/latest
