### ISSUE TITLE
pw.csv and pw_filled.csv missing

### ISSUE THREAD

**Issue by jasonchanhku** [ITMO-NSS-team/fedot_electro_ts_case#3]
Dear authors,

First and foremost thanks for creating such an incredible library. I was going through some example notebooks and realized that pw.csv and pw_filled.csv were missing. I tried looking on the internet but unfortunately can't find the dataset. Can the dataset be added into this repo? Thanks.

Regards,
Jason Chan

**Comment by Eldiias** [comment]
Agree with above. 
Waiting for the resolution of the issue.

**Comment by nicl-nno** [comment]
Hi!

At last, we added the files since they are become public.
However, this example is quite obsolete from technical side (since it aimed to fedot 0.3 and current version is 0.6.1+). You can find actual examples in https://github.com/ITMO-NSS-team/fedot-examples/tree/main/notebooks/latest
